services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - etl_network

  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+pymysql://airflow:airflow@mysql:3306/airflow
    volumes:
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - etl_network

  extractor:
    build:
      context: ./extractor
      dockerfile: Dockerfile
    environment:
      - SOURCE_MYSQL_HOST=${SOURCE_MYSQL_HOST}
      - SOURCE_MYSQL_USER=${SOURCE_MYSQL_USER}
      - SOURCE_MYSQL_PASSWORD=${SOURCE_MYSQL_PASSWORD}
      - SOURCE_MYSQL_PORT=${SOURCE_MYSQL_PORT}
      - SOURCE_MYSQL_DB=${SOURCE_MYSQL_DB}
      - DEST_MYSQL_HOST=${DEST_MYSQL_HOST}
      - DEST_MYSQL_USER=${DEST_MYSQL_USER}
      - DEST_MYSQL_PASSWORD=${DEST_MYSQL_PASSWORD}
      - DEST_MYSQL_PORT=${DEST_MYSQL_PORT}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      manager:
        condition: service_started
    command: tail -f /dev/null
    networks:
      - etl_network

  transformer:
    build:
      context: ./transformer
      dockerfile: Dockerfile
    environment:
      - SOURCE_MYSQL_HOST=${SOURCE_MYSQL_HOST}
      - SOURCE_MYSQL_USER=${SOURCE_MYSQL_USER}
      - SOURCE_MYSQL_PASSWORD=${SOURCE_MYSQL_PASSWORD}
      - SOURCE_MYSQL_PORT=${SOURCE_MYSQL_PORT}
      - SOURCE_MYSQL_DB=${SOURCE_MYSQL_DB}
      - DEST_MYSQL_HOST=${DEST_MYSQL_HOST}
      - DEST_MYSQL_USER=${DEST_MYSQL_USER}
      - DEST_MYSQL_PASSWORD=${DEST_MYSQL_PASSWORD}
      - DEST_MYSQL_PORT=${DEST_MYSQL_PORT}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      extractor:
        condition: service_started
    command: tail -f /dev/null
    networks:
      - etl_network

volumes:
  mysql_data:

networks:
  etl_network:
    driver: bridge