CREATE DATABASE IF NOT EXISTS etl_process;
CREATE DATABASE IF NOT EXISTS 5min_transform;
CREATE DATABASE IF NOT EXISTS 5min_today;
CREATE DATABASE IF NOT EXISTS 15min_today;
CREATE DATABASE IF NOT EXISTS mgw_today;
CREATE DATABASE IF NOT EXISTS airflow;
CREATE USER IF NOT EXISTS 'airflow'@'%' IDENTIFIED BY 'airflow';
GRANT ALL PRIVILEGES ON airflow.* TO 'airflow'@'%';
FLUSH PRIVILEGES;